rootProject.name = 'workshop-microservices'

include 'util', 'api'

include 'microservices:product-composite-service'
project(':microservices:product-composite-service').projectDir = file('microservices/product-composite-service')

// Os demais serviços serão incluídos quando forem incorporados ao monorepo.
